mysite/games/urls.py
# boiler plate code
from django.urls import path

# boiler plate code
from . import views

app_name = 'games' # this is useful for template URL namespaces

urlpatterns = [
    # ex: /games/
    path('',              views.index,    name='index'),
    path('settings',      views.settings, name='settings'),
    path('submit',        views.submit,   name='submit'),
    path('<int:game_id>', views.detail,   name='detail'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('first_app/', include('first_app.urls')),
    path('games/', include('games.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/games/models.py
from django.db import models


class Game(models.Model):
    title = models.CharField(max_length=200)
    provider = models.CharField(max_length=200)
    platform = models.CharField(max_length=200)
    type = models.CharField(max_length=50, null=True)
    year = models.IntegerField(blank=True, null=True)
    genre = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id) + " - " + self.title + " - " + self.platform + " - " + self.provider


class Settings(models.Model):
    sort_by = models.CharField(max_length=200, default="title")
    sort_reverse = models.BooleanField(default=True)
    show_id = models.BooleanField(default=True)
    show_title = models.BooleanField(default=True)
    show_provider = models.BooleanField(default=True)
    show_platform = models.BooleanField(default=True)
    show_type = models.BooleanField(default=True)
    show_year = models.BooleanField(default=True)
    show_genre = models.BooleanField(default=True)


class FieldVisibleAlways(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

mysite/games/views.py
import copy
import json

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template.defaulttags import register
from django.urls import reverse

from .models import FieldVisibleAlways, Game, Settings

@register.filter
def get_attr(object, key):
    reponse = None
    if hasattr(object, key):
        response = getattr(object, key, None)
    return response


def _fields_get(model_instance):
    field_list = []
    for field in model_instance._meta.get_fields():
        field_list.append(field.name)
    return field_list


def _fields_visible():
    fields = _fields_get(Game)
    settings = _settings_get()

    return_list = _fields_visible_always()
    for field in fields:
        field_setting_name = "show_" + field
        if hasattr(settings, field_setting_name):
            if getattr(settings, field_setting_name):
                if not field in return_list:
                    return_list.append(field)
    return return_list


def _fields_visible_always():
    return_list = ["id", "title"]
    for field in FieldVisibleAlways.objects.all():
        return_list.append(field.name)
    return return_list


def _fields_hidden():
    fields = _fields_get(Game)
    settings = _settings_get()
    fields_visible_always = _fields_visible_always()

    return_list = []
    for field in fields:
        field_setting_name = "show_" + field
        if hasattr(settings, field_setting_name):
            if not getattr(settings, field_setting_name):
                if not field in fields_visible_always:
                    return_list.append(field)
    return return_list


def _fields_that_are_hideable():
    return_list = _fields_get(Game)
    for field in _fields_visible_always():
        if field in return_list:
            return_list.remove(field)
    return return_list


def _fields_hideable_settings():
    """
    This is needed becuase I have yet to find a way in a template
    to get the field show setting along with the propety name just
    from the field list. It is easy with plain old Python code using
    getattr.

    return: A list of dicts with the each fields hideable settings. e.g.
    [
        {
            "field_name": "field_1",
            "field_setting_name": "show_field_1,
            "field_show": True,
        },
        ...
    ]
    """
    return_list = []
    fields_hideable = _fields_that_are_hideable()
    settings = _settings_get()
    for field in fields_hideable:
        field_setting_name = "show_" + field
        if hasattr(settings, field_setting_name):
            field_show = getattr(settings, field_setting_name)
            return_list.append(
                {
                    "field_name": field,
                    "field_setting_name": field_setting_name,
                    "field_show": field_show
                }
            )
    return return_list


def _detail_post(request):
    id = None

    if request.POST:
        body = request.POST
    elif request.body:
        body = json.loads(request.body)
    else:
        body = {}

    print("body=" + str(body))
    id = body.get("id")

    if id:
        print("id=" + str(id))
        game = Game.objects.get(pk=id)

        for field in body:
            if hasattr(game, field) and field != "id":
                value = body[field]
                setattr(game, field, value)
                print('setting "' + value + '" to the "' + field + '" field of id ' + body['id'])

        game.save()
    else:
        id=1

    return HttpResponseRedirect(reverse('games:detail', args=(body["id"],)))


def _index_post(request):
    print("title=" + request.POST["title"])
    print("provider=" + request.POST["provider"])
    print("platform=" + request.POST["platform"])
    game = Game(
        title=request.POST["title"],
        provider=request.POST["provider"],
        platform=request.POST["platform"],
        type=request.POST["type"]
    )
    game.save()
    return HttpResponseRedirect(reverse('games:detail', args=(game.id,)))


def _settings_get():
    try:
        settings = Settings.objects.all()[0]
    except:
        print("No settings found. A set was created.")
        settings = Settings()
        settings.save()
    return settings


def _settings_post(request):
    settings = _settings_get()
    settings_fields = _fields_get(Settings)
    print(request.POST)
    for field in settings_fields:
        if field in request.POST:
            if field == "sort_by":
                settings.sort_by = request.POST["sort_by"]
            elif field == "sort_reverse":
                if request.POST["sort_reverse"].lower() == "true":
                    print("sort_reverse is true")
                    settings.sort_reverse = True
                elif request.POST["sort_reverse"].lower() == "false":
                    print("sort_reverse is false")
                    settings.sort_reverse = False
            elif request.POST[field].lower() == "true":
                setattr(settings, field, True)
            else:
                setattr(settings, field, False)
        else:
            if "missing_means_unchecked" in request.POST:
                setattr(settings, field, False)
    settings.save()
    return HttpResponseRedirect(reverse('games:index'))


def _generate_table(model, never_show_fields=[], sort_by="title"):
    """
    return: a list that desribes a table. The first row has header info e.g.
    [
        [
            {"title": field1, "hide_button_show":False},
            ...
            {"title": fieldN, "hide_button_show":True}
        ]
        {"id": 1, "data": [ {"name": field1, "value": model1_field1}, ...  ] }
        ...
        {"id": M, "data": [ {"name": fieldM, "value": modelM_field1}, ... ] }
    """
    model_list = model.objects.all()
    field_list = _fields_visible()
    settings = _settings_get()
    fields_visible_always = _fields_visible_always()

    # remove fields to never show
    for field in never_show_fields:
        if field in field_list:
            field_list.remove(field)

    # create the headers
    header_list = []
    for field in field_list:
        title_attributes = {"title": field.capitalize()}
        title_attributes["hide_button_show"] = not field in fields_visible_always
        header_list.append(copy.deepcopy(title_attributes))

    # add all the rows
    table = []
    col = 0
    for model_instance in model_list:
        row = {}
        row["id"] = model_instance.id
        row["field"] = field_list[col:col+1]
        data = []
        for field in field_list:
            cell = {}
            cell["name"] = field
            cell["value"] = getattr(model_instance,field)
            data.append(cell)
        row["data"] = data
        table.append(row)
        col += 1

    # sort the table
    if sort_by in field_list:
        i = field_list.index(sort_by)
        # ref for this magic: https://stackoverflow.com/questions/18411560/sort-list-while-pushing-none-values-to-the-end
        table = sorted(table, key=lambda row: (row["data"][i]["value"] is None, row["data"][i]["value"]), reverse=settings.sort_reverse)

    table = [header_list] + table
    return table


def index(request):
    if request.POST:
        response = _index_post(request)
    else:
        settings = _settings_get()
        context = {
            "fields_hidden": _fields_hidden(),
            "settings": _settings_get(),
            "table": _generate_table(
                model=Game,
                never_show_fields=[],
                sort_by=settings.sort_by
            )
        }
        response = render(request, 'games/index.html', context)
    return response


def settings(request):
    if request.POST:
        response = _settings_post(request)
    else:
        context = {
            "field_list": _fields_get(Game),
            "settings": _settings_get(),
            "fields_hideable_settings": _fields_hideable_settings()
        }
        response = render(request, 'games/settings.html', context)
    return response


def submit(request):
    return render(request, 'games/submit.html', {})


def detail(request, game_id):
    print("request.method="+str(request.method))
    print("request.body="+str(request.body))
    if request.method == 'POST':
        print("!!! POST detected !!!")
        response = _detail_post(request)
    else:
        print("!!! Not a POST detected !!!")
        game = Game.objects.get(pk=game_id)
        fields = list(set(_fields_get(game)) - set(["id"]))
        context = {"game": game, "fields": fields}
        response = render(request, 'games/detail.html', context)
    return response

mysite/games/templates/games/detail.html
<html>
<body>
    <a href={% url 'games:index' %}>Home</a><br>
    ID={{ game.id }}
    <table border=1>
        <form action="{% url 'games:detail' game.id %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{ game.id }}" />
            {% for field in fields %}
                <tr>
                    <td>{{ field }}</td>
                    <td><input type="text" id="{{ field }}" name="{{ field }}" required value="{{ game|get_attr:field }}"></td>
                </tr>
            {% endfor %}
            <tr>
                <td></td>
                <td><input type="submit" value="Save changes"></td>
            </tr>
        </form>
    </table>

</body>
</html>

mysite/games/templates/games/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>TBD Title</title>
</head>
<body>
    <a href="{% url 'games:submit' %}">Submit</a> a game.
    <a href="{% url 'games:settings' %}">Settings</a></br>
    <table><tr>
        <td>
            <label id="unhide_cols">Unhide columns:</label>
        </td>

        {% for field in fields_hidden %}
            <td><form action="{% url 'games:settings' %}" method="post" style="margin: 0px;">
                {% csrf_token %}
                <input type="hidden" name="show_{{ field }}" value="true">
                <input type="submit" value="{{ field | title }}">
            </form></td>
        {% endfor %}

    </tr></table>
    <div id="log">log</div>
    {% csrf_token %}
    <table border=1>
        <tr>
            {% for header in table.0 %}
                {% if header %}
                    <td>
                        <b>{{ header.title }}</b>
                        <br>
                        <table>
                            <tr>
                                <td><form action="{% url 'games:settings' %}" method="post" style="margin: 0px;">
                                    {% csrf_token %}
                                    <input type="hidden" name="sort_by" value="{{ header.title | lower }}">
                                    <input type="hidden" name="sort_reverse" value="false">
                                    <input type="submit" value="v">
                                </form></td>
                                <td><form action="{% url 'games:settings' %}" method="post" style="margin: 0px;">
                                    {% csrf_token %}
                                    <input type="hidden" name="sort_by" value="{{ header.title | lower }}">
                                    <input type="hidden" name="sort_reverse" value="true">
                                    <input type="submit" value="^">
                                </form></td>
                            </tr>
                            {% if header.hide_button_show %}
                                <tr>
                                    <td colspan="2"><form action="{% url 'games:settings' %}" method="post" style="margin: 0px">
                                        {% csrf_token %}
                                        <input type="hidden" name="show_{{ header.title | lower }}" value="false">
                                        <input type="submit" value="Hide">
                                    </form></td>
                                </tr>
                            {% endif %}
                        </table>
                    </td>
                {% endif %}
            {% endfor %}
        </tr>
        {% for row in table %}
            {% if not forloop.first %}
                <form action="{% url 'games:detail' row.id %}" method="post">
                    <tr>
                        {% for field in row.data %}
                            <td>
                                {% if field.name == "id" %}
                                    <a href="{% url 'games:detail' row.id %}">{{ row.id }}</a>
                                {% else %}

                                    <input type="text"
                                           size="{% if field.value|length == 0 %}1{% else %}{{ field.value|length }}{% endif %}"
                                           id="{{ row.id }}.{{ field.name }}"
                                           name="{{ field.name }}"
                                           value="{{ field.value }}"
                                           onblur="post_field( '{{ row.id }}', '{{ field.name }}' ,'{{ field.value }}' )"
                                    >
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                </form>
            {% endif %}
        {% endfor %}
    </table>
</body>

<script>
    function post_field(id, field, inital_value){
        console.log("id=" + id + ", field=" + field + " inital_value=" + inital_value)
        let cell_id = id + "." + field;
        let new_value = document.getElementById(cell_id).value;
        console.log("new_value=" + new_value);
        if (inital_value != new_value){
            console.log("new_value is different than the pervious value");
            let payload = {}
            payload["id"] = id
            payload[field] = new_value
            rest_post("{% url 'games:index' %}" + id, payload)
            document.getElementById('log').innerHTML = "id=" + id + " field=" + field + ' changed to: "' + new_value + '"';
            document.getElementById(cell_id).onblur = function onblur(event) {post_field( id, field , new_value )};
        }
        else{
            console.log("new_value is the same as the pervious value");
        }
    }

    function rest_post(url, data){
        console.log("rest_post(" + url + "," + data + ") was called.")

        fetch(
            url,
            {
                headers: { "Content-Type": "application/json",
                           "X-CSRFToken": document.querySelector('[name=csrfmiddlewaretoken]').value},
                body: JSON.stringify(data),
                method: "POST"
            }
        )
        //.then(data => data.json())
        //.then((json) => {
        //    alert(JSON.stringify(json));
        //});
    }
</script>
</html>

mysite/games/templates/games/settings.html
<html>
    <title>TBD Title</title>
<body>
    <a href={% url 'games:index' %}>Home</a><br>
    <form action="{% url 'games:settings' %}" method="post">
    {% csrf_token %}
    <table>
        <tr>
            <td>
                <label name="sort_by">Sort by:</label>
            </td>
            <td><select name="sort_by" value="{{ settings.sort_by }}">
                {% for field in field_list %}
                    <option value="{{ field }}" {% if settings.sort_by == field %}selected{% endif %}>
                        {{ field }}
                    </option>
                {% endfor %}
            </select></td>
        </tr>
        <tr>
            <td>
                <label name="sort_reverse">Sort reverse</label>
            </td>
            <td>
                <input type="hidden" name="missing_means_unchecked">
                <input type="checkbox"
                       name="sort_reverse"
                       id="sort_reverse"
                       value="true"
                       {% if settings.sort_reverse %} checked {% endif %}>
            </td>
        </tr>
        {% for field in fields_hideable_settings %}
            <tr>
                <td>Show {{ field.field_name }}:</td>
                <td>
                    <input type="hidden" name="missing_means_unchecked">
                    <input type="checkbox"
                           name="show_{{ field.field_name }}"
                           id="show_{{ field.field_name }}"
                           value="true"
                           {% if field.field_show  %} checked {% endif %}>
                </td>
            </tr>
         {% endfor %}
    </table>
    <input type="submit" value="Save changes">
    </form>
</body>
</html>

mysite/games/templates/games/submit.html
<html>
<body>
    <a href={% url 'games:index' %}>Home</a><br>
    <form action="{% url 'games:index' %}" method="post">
        {% csrf_token %}
        <table>
            <tr>
                <td><label for="title">Title:</label></td>
                <td><input type="text" id="title" name="title" required></td>
            </tr>
            <tr>
                <td><label for="platform">Platform:</label></td>
                <td>
                    <select name="platform" id="platform" size="1" required>
                    <option value="PS3">PS3</option>
                    <option value="PS4">PS4</option>
                    <option value="PS5">PS5</option>
                    <option value="Xbox360">Xbox360</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td><label for="provider">Provider:</label></td>
                <td><input type="text" id="provider" name="provider" required></td>
            </tr>
            <tr>
                <td><label for="type">Type:</label></td>
                <td><input type="text" id="type" name="type" required></td>
            </tr>
        </table>
        <input type="submit" value="Submit">
    </form>

</body>
</html>